# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=255)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BallPocketed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_called', models.BooleanField(default=False)),
                ('is_slop', models.BooleanField(default=False)),
                ('ball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ball')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name=b'date started')),
                ('ended_at', models.DateTimeField(verbose_name=b'date ended')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_winner', models.BooleanField(default=False)),
                ('pattern', models.CharField(max_length=255, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=255)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_turn', models.IntegerField(default=0)),
                ('number_in_game', models.IntegerField(default=0)),
                ('is_success', models.BooleanField(default=False)),
                ('is_break', models.BooleanField(default=False)),
                ('called_ball', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ball')),
                ('called_pocket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Pocket')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Player')),
            ],
        ),
        migrations.AddField(
            model_name='shot',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Turn'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Player'),
        ),
        migrations.AddField(
            model_name='ballpocketed',
            name='pocket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pocket'),
        ),
        migrations.AddField(
            model_name='ballpocketed',
            name='shot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Shot'),
        ),
    ]
