# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shot_is_following_scratch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallRemaining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ball')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Shot')),
            ],
        ),
    ]
