# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ballremaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='combo_count',
            field=models.IntegerField(default=1),
        ),
    ]
