# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_shot_is_scratch'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='is_table_open',
            field=models.BooleanField(default=False),
        ),
    ]
