# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 19:05
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170826_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='guest_code',
            field=models.CharField(default=api.models.generate_guest_code, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
