# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170827_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_giver_set', to='api.Player')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_taker_set', to='api.Player')),
            ],
        ),
    ]
