# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 17:06
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_table_tablemember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='guest_code',
        ),
        migrations.AddField(
            model_name='invitation',
            name='is_guest_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='guest_invitation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Invitation'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(default=api.models.generate_invitation_code, max_length=255),
        ),
    ]
